Docs 5945 insight topic limitations hn
mulesoft/docs-runtime-manager pull request #265
Opened 2020-01-11 17:05 UTC by hannanelson

Cleaned up topic, updated screenshots, added MIME type info to address confusion in (SE-12363 and SE-12535), clarified Replay.

Here's a PDF:

[5-after-Insight _ MuleSoft Documentation.pdf](https://github.com/mulesoft/docs-runtime-manager/files/4049567/5-after-Insight._.MuleSoft.Documentation.pdf)

2020-01-13 20:27 UTC, mcocaro approved these changes

2020-01-15 13:51 UTC, rodrigo-neira requested changes
Hi @hannanelson , Once I raised this https://www.mulesoft.org/jira/browse/DOCS-3930 to explicitly say that Mule 4 does not support replay topic. In the new docs (attached pdf) I can't see the explicit statement for this. Like here: https://docs.mulesoft.com/runtime-manager/insight#fix-then-replay

Please explicitly add it, if not customers think that it may be possible to do it and then raise tickets mentioning that it's not working in Mule 4.

In the pdf attached it says "Replay Transaction (Mule 3 apps)", for me that is not enough, as customers will ask themselves... and what about Mule 4? How can I achieve it? 

Thank you!

2020-01-15 15:47 UTC, rodrigo-neira approved these changes
Thanks @hannanelson , it looks fine to me now :)

2020-01-15 20:17 UTC, kbostrom approved these changes
Here you go!
Please feel free to query me about confusing comments, or educate me when a suggestion has changed your intended meaning!

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> -Insight is a troubleshooting tool that gives you in-depth visibility into business transactions and events on your Mule apps deployed through Runtime Manager. Insight makes information searchable and
Edit instructions:

I have a PR for you to review. Rewrite/refresh of a topic + some new content. It says 17 files, but it's really just the one (insight.adoc). Sometime tomorrow? Thanks!

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +For information on tools to use for monitoring a production environment, see xref:monitoring.adoc[Monitoring Applications and Servers].
information on > information about
GLOBAL

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +For Mule 3 apps only, Insight supports the ability to replay transactions for advanced error recovery. Replay is not supported for Mule 4 apps.
Do we need this restatement?

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +* Data that passes through endpoints (inbound and outbound) in your Mule applications
Not worded as an event, per list intro.
"Data passing through endpoints..."?

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +Insight does not preserve replay data when switching regions. Ensure that this doesn't violate any of your compliance requirements.
Do we need to remind audience that this applies only to M3?

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +Logs for applications deployed to on-premises servers contain event information, but not message contents.
```suggestion
Logs for applications deployed to on-premises servers contain event information but not message contents.
```

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +Replay data for applications created before October 7, 2017 is stored in the default region, us-east-1.
```suggestion
Replay data for applications created before October 7, 2017, is stored in the default region us-east-1.
```

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +Data for applications deployed, or deployed to a different region, after October 7, 2017 is stored in the region where the application is deployed.
I did not understand the difference between deployed and to a different region at first, so I think this probably needs rewording:
"Data for applications (initially?) deployed or (redeployed? moved?) to a different region after October 7, 2017, is stored in the region where the application is (most recently?) deployed.

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +The following MIME types are always mapped as Strings.
```suggestion
The following MIME types are always mapped as Strings:
```

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +----
Should these be in alpha order if no other?

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +For all other types, Mule Agent attempts to transform payloads to another format, based on the Stream type that Mule runtime engine exposes to the Mule Agent.
Mule Agent?
I haven't seen this term yet.
When I look it up, I see first references to Anypoint Runtime Manager agent and, later, in blog posts, Mule agent.

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +For example, Mule Agent converts payloads in `CURSOR_STREAM_PROVIDER` type to a byte array.
Do we need "type" if we format the name as syntax?

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +Any Streams that are not mapped to String by default appear in the logs.
Should this be...:
```suggestion
Any streams that are not mapped to String by default appear in the logs. 
```

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +** *Metadata and Replay* to track events and enable the ability to instantly replay a transaction from the console.
no period
```suggestion
** *Metadata and Replay* to track events and enable the ability to instantly replay a transaction from the console
```

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +For more information, see <<Diagnosing Problems and Replaying Transactions>>.
Is this a placeholder for a xref?

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +. Select the checkbox to confirm that you want to enable Insight and click *Apply Changes*.
```suggestion
. Select the checkbox to confirm that you want to enable Insight, and click *Apply Changes*.
```

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +Logical groupings of related events that often correspond to a business view of the system.
Not a sentence; no period:
```suggestion
Logical groupings of related events that often correspond to a business view of the system
```

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +Low-level details of a transaction.
ditto
```suggestion
Low-level details of a transaction
```

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +Customized key-value pairs that you specify as part of custom events in your application.
```suggestion
Customized key-value pairs that you specify as part of custom events in your application
```

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +Business data, if configured, appear in the Metadata area (*3*) of the dashboard. See <<Setting Up Business Events>>.
```suggestion
Business data, if configured, appears in the Metadata area (*3*) of the dashboard. See <<Setting Up Business Events>>.
```
Is << >> OK?

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +* Transactions according to flow name, exception message, processing time, and/or any custom business data
Avoid "and/or" and use instead the most likely or common for the context. GLOBAL

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +To enable the *Business Data* field your app must have business events configured. See <<Setting Up Business Events>>.
I'll stop asking about << >>

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +For all other types, Mule Agent attempts to transform payloads to another format, based on the Stream type that Mule runtime engine exposes to the Mule Agent.
I just got weigh-in from PMM: Mule agent

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +* To display only failed or completed transactions, select *Failed* or *Completed* from the menu in the *Transaction ID* field.
colon
```suggestion
* To display only failed or completed transactions, select *Failed* or *Completed* from the menu in the *Transaction ID* field:
```

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +Alternatively, click and drag within the graph to select a specific date range:
```suggestion
Alternatively, drag within the graph to select a specific date range:
```

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +* To edit a saved search, hover the mouse over the search name, and then click the *Edit* link.
```suggestion
* To edit a saved search, hover over the search name and click the *Edit* link:
```

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +. If you want to save a search, click *Save search*:
I don't think that the actions performed on a saved search are really subordinate tasks to saving a search: running, editing, and deleting.

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +Click to expand the transaction, then examine the individual events within that transaction. The exception and the error message are listed next to the failed event, as well as an existing stack trac
```suggestion
Click to expand the transaction, and then examine the individual events within that transaction. The exception and the error message are listed next to the failed event, as well as an existing stack trace:
```

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +=== Replay Transaction (Mule 3 apps only)
I suggest putting the parenthetical qualification into the text directly following the title rather than in it.

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +Replay is not supported for Mule 4 apps.
Nec?

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +. Click the replay icon (circular arrow) to the right of the first event in the failed transaction to replay it:
I just saw Valkyrie use a screen cap for an icon; suggest the same here.

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +. Click the replay icon (circular arrow) to the right of the first event in the failed transaction to replay it:
Also, if we show it in the capture directly following, we might not need to describe it here.

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +=== Purge Replay Transaction Data
This head does not use qualifier, so why use it earlier? They are peers after all.

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +== Insight Status States
Table of Insight Status States?
No intro text to set a context for the table?

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +|`FAILED`|The event failed while being processed and has an associated exception associated.
```suggestion
|`FAILED`|The event failed while being processed and has an associated exception.
```

2020-01-15 20:17 UTC, kbostrom commented on modules/ROOT/pages/insight.adoc
> +|`STALLED`|The event has been put on hold due to the maximum number of events to be processed per transaction (10000). Any event above this mark is set as stalled and then processed after this event
```suggestion
|`STALLED`|The event has been put on hold due to exceeding the maximum number of events to be processed per transaction (10000). Any event above this number is set as stalled and then processed after the number of events to be processed is no longer exceeded.
```

2020-01-15 20:17 UTC, kbostrom approved these changes
Here you go!
Please feel free to query me about confusing comments, or educate me when a suggestion has changed your intended meaning!

2020-01-15 21:26 UTC, hannanelson commented on modules/ROOT/pages/insight.adoc
> +For Mule 3 apps only, Insight supports the ability to replay transactions for advanced error recovery. Replay is not supported for Mule 4 apps.
Yes.

2020-01-15 21:31 UTC, hannanelson commented on modules/ROOT/pages/insight.adoc
> +For more information, see <<Diagnosing Problems and Replaying Transactions>>.
No, it's an intra-topic xref.

2020-01-16 15:07 UTC, merged