Addressed issue, moved VPC section.
mulesoft/docs-runtime-manager pull request #284
Opened 2020-02-06 23:05 UTC by hannanelson

Also moved VPC section to be closer to CloudHub content.

2020-02-11 15:55 UTC, sjsheridan requested changes
#287 supersedes the "Open a Support ticket.." change made here.

2020-02-11 20:54 UTC, Terry-He approved these changes

2020-02-11 20:59 UTC, hannanelson commented
> #287 supersedes the "Open a Support ticket.." change made here.

I will address the edits required for #287 in another sprint.

2020-02-11 21:01 UTC, wwarner-salesforce approved these changes

2020-02-12 20:07 UTC, sjsheridan approved these changes

2020-02-12 20:21 UTC, merged