Added naming guidelines.
mulesoft/docs-runtime-manager pull request #358
Opened 2020-06-04 00:30 UTC by hannanelson

Please check the server naming guidelines.

2020-06-04 22:21 UTC, raogautham submitted a review, later dismissed
Good. Thanks!

2020-06-08 17:48 UTC, aljrubior approved these changes
LGTM

2020-06-11 17:21 UTC, dhirsch1 submitted a review, later dismissed

2020-06-18 10:35 UTC, aljrubior requested changes

2020-06-18 10:35 UTC, aljrubior commented on modules/ROOT/pages/servers-create.adoc
> +Server names can contain up to 60 alphanumeric characters (a-z, A-Z, 0-9), periods (.), and hyphens (-), but not spaces or other characters.
Can we please add the Underscore character `_` ?

Currently in prod we found the following non-alphanumeric characters in Server's names (Server count):
* `_` 3722
* `.` 4722
* `-` 53010

IMPORTANT!
We allow the use of Japanese characters in Server's and Application's name.

Ex. The following names are valid in our platform
* Sever: 日本のサーバー
* Application: 日本のアプリケーション

2020-06-23 19:51 UTC, aljrubior approved these changes
LGTM

2020-06-23 19:52 UTC, aljrubior approved these changes
LGTM

2020-06-23 19:55 UTC, wwarner-salesforce approved these changes

2020-06-23 19:56 UTC, merged