Docs 3526 app versioning
mulesoft/docs-runtime-manager pull request #37
Opened 2018-11-29 18:44 UTC by valkyrie69

Please provide a technical review--feedback/corrections/anything

NOTE: The decision about *where* in the navigation this documentation will be has not been made yet.

2018-11-30 14:27 UTC, mcocaro requested changes
Added some comments

2018-11-30 14:27 UTC, mcocaro commented on modules/ROOT/pages/app-versioning.adoc
> +** The application ZIP file
maybe application artifact instead? to avoid calling out zip for mule 3 and jar for mule4

2018-11-30 14:27 UTC, mcocaro commented on modules/ROOT/nav.adoc
> + ** xref:app-versioning.adoc[Application Versioning]
do you think its better to move this file to Runtime Fabric section? check this page in which it refers to deploying applications in RTF: https://docs.mulesoft.com/runtime-fabric/1.0/deploy-to-runtime-fabric

2018-11-30 14:27 UTC, mcocaro commented on modules/ROOT/pages/app-versioning.adoc
> +** Application version
is this the artifact version? if so, I would consider it as part of changing the application deployment artifact

2018-11-30 14:27 UTC, mcocaro commented on modules/ROOT/pages/app-versioning.adoc
> +** Ingress and property values
missing STATUS as a part of the versioning here

2018-11-30 14:27 UTC, mcocaro commented on modules/ROOT/pages/app-versioning.adoc
> +* Started (green): The replica is receiving traffic.
should we instead update and link to this page? https://docs.mulesoft.com/runtime-manager/managing-deployed-applications#status-states

2018-11-30 14:27 UTC, mcocaro commented on modules/ROOT/pages/app-versioning.adoc
> +New configurations are applied as "rolling updates." For example, a replica is created with the desired configuration, and once that configuration is successfully applied, the replica with the old co
can we include a note here to note that applications that cannot run multiple versions in parallel should consider this?

2018-11-30 14:27 UTC, mcocaro commented on modules/ROOT/pages/app-versioning.adoc
> +In cases of failure, the deployment is rolled back to the last successful version of the configuration, but the status of the configuration still displays "Updated failed."
there are scenarios in which k8s will not rollback new configurations, lets add here that it is on a best-intention basis but not guaranteed.

2018-11-30 14:27 UTC, mcocaro commented on modules/ROOT/pages/app-versioning.adoc
> += Application Versioning
can we add a text to explain that what's being versioned is the Deployment (Application + Configuration) automatically by ARM?

2018-11-30 16:14 UTC, valkyrie69 commented on modules/ROOT/nav.adoc
> + ** xref:app-versioning.adoc[Application Versioning]
This is what I mentioned--Steven and I are going to talk about the best placement for this with Sundip. I am thinking it will likely be moved to RTF.

2018-11-30 16:17 UTC, valkyrie69 commented on modules/ROOT/pages/app-versioning.adoc
> +* Started (green): The replica is receiving traffic.
I don't know about this.  The replica statuses seem to have parity with Kubernetes statuses and slightly different from the application statuses mentioned on the page you mention. We can talk about this.

2018-11-30 16:26 UTC, valkyrie69 commented on modules/ROOT/pages/app-versioning.adoc
> +** The application ZIP file
Changed to "application package."

2018-11-30 16:54 UTC, valkyrie69 commented on modules/ROOT/pages/app-versioning.adoc
> += Application Versioning
Changed the text. You will need to re-review.

2018-11-30 16:54 UTC, valkyrie69 commented on modules/ROOT/pages/app-versioning.adoc
> +In cases of failure, the deployment is rolled back to the last successful version of the configuration, but the status of the configuration still displays "Updated failed."
Changed the text. You can re-review.

2018-11-30 17:04 UTC, valkyrie69 commented on modules/ROOT/pages/app-versioning.adoc
> +** Ingress and property values
Added.

2018-11-30 17:04 UTC, valkyrie69 commented on modules/ROOT/pages/app-versioning.adoc
> +New configurations are applied as "rolling updates." For example, a replica is created with the desired configuration, and once that configuration is successfully applied, the replica with the old co
Added a note, but you will probably want to re-review. I'm not sure if it needs more context.

2018-11-30 17:19 UTC, mcocaro commented on modules/ROOT/pages/app-versioning.adoc
> +* Started (green): The replica is receiving traffic.
agree on that - however, if I'm a user and want to search more on replica status, the least place I'd look is Application Versioning. would you agree?

2018-12-03 18:58 UTC, PabloMR92 commented on modules/ROOT/pages/app-versioning.adoc
> +Applications can't run multiple versions in parallel.
I would remove this one, since rolling update means that there are different versions running at the same time

2018-12-03 22:21 UTC, valkyrie69 commented on modules/ROOT/pages/app-versioning.adoc
> +* Started (green): The replica is receiving traffic.
I added a section to managing-deployed-applications#status-states for Replica statuses. But I am keeping the statuses in both places so the users don't have to click off the page to see the info about statuses. Especially if we decide the app versioning doc should be in Runtime Fabric (different product from Runtime Manager).

2018-12-04 15:51 UTC, mcocaro commented on modules/ROOT/pages/app-versioning.adoc
> +* Started (green): The replica is receiving traffic.
sounds good!

2018-12-04 15:53 UTC, mcocaro approved these changes
LGTM!

2018-12-10 19:20 UTC, merged