Added info on RTM agent/proxy and link to troubleshooting
mulesoft/docs-runtime-manager pull request #397
Opened 2020-09-23 20:13 UTC by hannanelson

2020-09-23 20:17 UTC, rtom-mulesoft approved these changes, later dismissed

2020-09-24 16:56 UTC, aljrubior approved these changes
LGTM

2020-09-24 17:15 UTC, aljrubior requested changes

2020-09-24 17:15 UTC, aljrubior commented on modules/ROOT/pages/rtm-agent-proxy-config.adoc
> +== Verify That the Proxy Server Does Not Modify the Agent Certificate
Verify That the Proxy Server Does Not Modify the **Runtime Manager Certificate**

2020-09-24 17:25 UTC, aljrubior commented on modules/ROOT/pages/rtm-agent-proxy-config.adoc
> +echo -e "GET / HTTP/1.0\r\n" | openssl s_client -connect mule-manager.anypoint.mulesoft.com:443 -ign_eof
Taking into consideration that 
- Old agents use `mule-manager.anypoint.mulesoft.com`
- Newer agent's use `runtime-manager.anypoint.mulesoft.com` (+1.12.0 and +2.2.0) 

I think we better use `runtime-manager.anypoint.mulesoft.com` for reference.

Run the command with either host will probe if the firewall or proxy is tampering the certificate

2020-09-24 17:27 UTC, aljrubior commented on modules/ROOT/pages/rtm-agent-proxy-config.adoc
> +subject=/C=US/O=Hybrid/OU=MuleSoft/CN=mule-manager.anypoint.mulesoft.com
For `runtime-manager.anypoint.mulesoft.com`

the output would be

`
-----END CERTIFICATE-----
subject=/C=US/ST=ca/L=San Francisco/O=MuleSoft, LLC/OU=Mulesoft/CN=runtime-manager.anypoint.mulesoft.com
issuer=/C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
---`

2020-09-24 17:27 UTC, aljrubior approved these changes

2020-09-24 17:28 UTC, aljrubior requested changes
Leave some comments

2020-09-24 19:13 UTC, aljrubior approved these changes
LGTM

2020-09-28 19:22 UTC, kbostrom approved these changes
Edited per scope of request: no comments

2020-09-28 21:44 UTC, merged