[EXC-7876] Exchange mutable data endpoint
mulesoft/docs-runtime-manager pull request #545
Opened 2021-09-09 20:48 UTC by LucasLudueno

Adding exchange mutable data endpoint

2021-09-10 13:56 UTC, lucasVoboril commented on modules/ROOT/pages/anypoint-platform-cli-commands.adoc
> +`([_groupID_]/)_assetID_/_version_`
😂  I had also done it in this way, but we are not using this format for optional arguments. Check this

https://github.com/mulesoft/docs-runtime-manager/pull/521#discussion_r668241713

```suggestion
`[_<groupID>_]/_<assetID>_/_<version>_`
```

2021-09-10 20:00 UTC, constanzaderienzo requested changes

2021-09-10 20:00 UTC, constanzaderienzo commented on modules/ROOT/pages/anypoint-platform-cli-commands.adoc
> +This command modify mutable data (tags, categories, fields and documentation) to an already created asset.
```suggestion
This command modifies the mutable data (tags, categories, fields and documentation) of an already created asset. 
```

2021-09-10 22:39 UTC, lucasVoboril approved these changes, later dismissed

2021-09-13 15:49 UTC, Igua95 submitted a review, later dismissed

2021-09-14 13:26 UTC, constanzaderienzo submitted a review, later dismissed

2021-09-22 20:43 UTC, wwarner-salesforce approved these changes

2021-09-27 13:33 UTC, Igua95 approved these changes

2021-09-28 12:51 UTC, merged