DOCS-12719 CH deployment JDK version
mulesoft/docs-runtime-manager pull request #579
Opened 2021-12-08 02:32 UTC by luanamulesoft

2021-12-09 19:50 UTC, nishantkakar requested changes

2021-12-09 19:50 UTC, nishantkakar commented on modules/ROOT/pages/deployment-strategies.adoc
> +Mule runtime 3.9.x and 4.1.x support JDK 8. Mule runtime 4.2.x and later support JDK 8 and JDK 11.
As this is for Cloudhub only I would not mention JDK 11

2021-12-13 18:58 UTC, nishantkakar approved these changes

2021-12-13 22:49 UTC, sathya0 approved these changes

2021-12-13 22:55 UTC, merged