W-12397480-Kerberos-support
mulesoft/docs-runtime-manager pull request #648
Opened 2023-01-19 19:08 UTC by luanamulesoft

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2023-01-27 12:48 UTC, rodrisouto approved these changes, later dismissed
lgtm

2023-01-27 14:41 UTC, lggomezsf requested changes

2023-01-27 14:41 UTC, lggomezsf commented on runtime-manager/modules/ROOT/pages/rtm-agent-proxy-config.adoc
> +If the proxy server doesn't require authentication, omit _proxy-user_ and _proxy-password_. These options are required when using Kerberos authentication via _--use-kerberos-proxy_.
@rodrisouto this last line isn't true any longer right?
Otherwise the PR LGTM

2023-01-27 14:41 UTC, lggomezsf submitted a review, later dismissed

2023-01-27 14:44 UTC, rodrisouto commented on runtime-manager/modules/ROOT/pages/rtm-agent-proxy-config.adoc
> +If the proxy server doesn't require authentication, omit _proxy-user_ and _proxy-password_. These options are required when using Kerberos authentication via _--use-kerberos-proxy_.
why is it not true? they user and password are required for `--use-kerberos-proxy`

2023-01-27 20:08 UTC, sathya0 commented on runtime-manager/modules/ROOT/pages/rtm-agent-proxy-config.adoc
> +The Runtime Manager agent supports supports the basic access and Kerberos v5 (via SPNEGO) authentication schemes for proxied communication.
```suggestion
The Runtime Manager agent supports the basic access and Kerberos v5 (via SPNEGO) authentication schemes for proxied communication.
```

2023-01-27 20:08 UTC, sathya0 commented on runtime-manager/modules/ROOT/pages/rtm-agent-proxy-config.adoc
> +For Kereros authentication, use the new parameter to specify that this protocol will be used along with the configuration file paths.
```suggestion
For Kerberos authentication, use the new parameter to specify that this protocol will be used along with the configuration file paths.
```

2023-01-27 20:12 UTC, sathya0 approved these changes

2023-01-30 14:36 UTC, lggomezsf approved these changes

2023-01-31 16:01 UTC, merged