Adding new DNS for MCM and AuthProxy
mulesoft/docs-runtime-manager pull request #66
Opened 2019-01-24 13:03 UTC by aljrubior

2019-01-24 13:12 UTC, mcocaro requested changes
can you please include a copy text that states that the new DNS endpoints do not have a static IP pls? Thx

2019-01-24 19:15 UTC, valkyrie69 requested changes
One minor edit requested.

2019-01-24 19:15 UTC, valkyrie69 commented on modules/ROOT/pages/installing-and-configuring-runtime-manager-agent.adoc
> +[NOTE]
Please change to:

The following DNS endpoints do not have static IP addresses:

2019-01-25 19:32 UTC, mcocaro approved these changes
LGTM

2019-01-25 19:49 UTC, valkyrie69 approved these changes

2019-01-26 23:19 UTC, merged