W-14497696-rtm-distributed-tracing-beta
mulesoft/docs-runtime-manager pull request #710
Opened 2023-12-05 18:38 UTC by luanamulesoft

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2024-03-01 21:44 UTC, sarathecoubian approved these changes, later dismissed

2024-03-05 20:48 UTC, rithishapadmanabh commented on runtime-manager/modules/ROOT/pages/deployment-strategies.adoc
> +     - Once you enable tracing, the Runtime Manager backend starts instrumenting traces for your application.
Change to
`Once you enable tracing, and redeploy the application, the Runtime Manager backend starts instrumenting traces for your application.
`

2024-03-05 20:49 UTC, rithishapadmanabh requested changes, later dismissed
Change to
"Once you enable tracing, and redeploy the application, the Runtime Manager backend starts instrumenting traces for your application. "

2024-03-05 23:41 UTC, JennyHajee approved these changes

2024-03-06 22:46 UTC, merged