W-14749816-rtm-ch-mule46-release-cadence
mulesoft/docs-runtime-manager pull request #714
Opened 2024-01-03 20:22 UTC by luanamulesoft

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2024-01-25 20:12 UTC, rithishapadmanabh requested changes
1. With this release, the update available tab is going away and a new update available column with minor, patch and build as possible update types. We need to update docs for that
2. I can't find a clear call out that it is not just monthly date patches, but we also now also have auto-minor upgrades/updates (-- whatever is the chosen terminology), when a new minor version is released for the Edge channel. The sections under Monthly date patch -- i.e update schedule, update notification all need to be created for Auto minor upgrades as well. 
3. We do not yet support setting up alerts for autoupdate failures, so we should remove that.
4. JDK --> should be changed to Java
5. We can add a screenshot + mention for the new Java column that indicates java version installed in the target in the Servers page.
6. Autoupdate related changes are also required in Cloudhub 2.0 -- https://docs.mulesoft.com/cloudhub-2/ch2-patch-updates [ the page url / title should change from just patch updates to something more generic like "runtime and infra" upgrades, and have a separate section for Runtime updates (not just patches, but minor upgrades as well).

2024-01-25 20:12 UTC, rithishapadmanabh commented on cloudhub/modules/ROOT/pages/cloudhub-app-runtime-version-updates.adoc
> +To be notified by e-mail when an error occurs after an automated update, you can xref:alerts-on-runtime-manager.adoc#create-an-alert[create an alert].
This behavior is not available today, let us remove after confirmation with engg

2024-01-25 20:12 UTC, rithishapadmanabh commented on runtime-manager/modules/ROOT/pages/deployment-strategies.adoc
> +|CloudHub 2.0 | JDK 8, JDK 17 | xref:release-notes::cloudhub-2/cloudhub-2-runtimes-release-notes.adoc[]
We should use Java everywhere (this was decided for UX as well) instead of JDK.

2024-01-25 20:12 UTC, rithishapadmanabh commented on runtime-manager/modules/ROOT/pages/deploying-to-your-own-servers.adoc
> +* All servers in a server cluster are on the same Java version, and the target Java version matches that of the application.
This is useful. Can we also call out that customers can also view the java version associated with their target through the Servers page: https://anypoint.mulesoft.com/cloudhub/#/console/home/servers

2024-01-25 20:12 UTC, rithishapadmanabh commented on cloudhub/modules/ROOT/pages/cloudhub-app-runtime-version-updates.adoc
> +To be notified by e-mail when an error occurs after an automated update, you can xref:alerts-on-runtime-manager.adoc#create-an-alert[create an alert].
These updates are also required in the Cloudhub 2.0 updates page: https://docs.mulesoft.com/cloudhub-2/ch2-patch-updates

2024-01-31 15:58 UTC, luanamulesoft commented on cloudhub/modules/ROOT/pages/cloudhub-app-runtime-version-updates.adoc
> +To be notified by e-mail when an error occurs after an automated update, you can xref:alerts-on-runtime-manager.adoc#create-an-alert[create an alert].
I confirmed this info with the Eng team (Matias Bruchi). These options are already available today and serve the purpose of checking the status of apps after an auto-upgrade.
For CH2, I'll coordinate with Sara for her to add this to CH2 content.

2024-01-31 16:01 UTC, luanamulesoft commented on runtime-manager/modules/ROOT/pages/deployment-strategies.adoc
> +|CloudHub 2.0 | JDK 8, JDK 17 | xref:release-notes::cloudhub-2/cloudhub-2-runtimes-release-notes.adoc[]
I'll create a task in GUS to work in this change.

2024-02-01 18:52 UTC, matbruc commented on cloudhub/modules/ROOT/pages/cloudhub-app-runtime-version-updates.adoc
> +To be notified by e-mail when an error occurs after an automated update, you can xref:alerts-on-runtime-manager.adoc#create-an-alert[create an alert].
What is available is the ability to check a deployment failure cause and logs. Although, this information of the deployment won't differentiate if it is a auto update, auto upgrade or manual update.

2024-02-01 20:43 UTC, rithishapadmanabh requested changes, later dismissed
I still don't see the following review comments from the last review addressed. Is that part of a different PR?

1. With this release, the update available 'tab' is going away and a new update available column with minor, patch and build as possible update types. We need to update docs for that. --> I still see mention of the 'tab'
2. I can't find a clear call out that it is not just monthly date patches, but we also now also have auto-minor upgrades/updates (-- whatever is the chosen terminology), when a new minor version is released for the Edge channel. The sections under Monthly date patch -- i.e update schedule, update notification all need to be created/extended for Auto minor upgrades as well.

2024-02-01 20:43 UTC, rithishapadmanabh commented on cloudhub/modules/ROOT/pages/cloudhub-app-runtime-version-updates.adoc
> +To be notified by e-mail when an error occurs after an automated update, you can xref:alerts-on-runtime-manager.adoc#create-an-alert[create an alert].
In that case @luanamulesoft can we modify to 
To be notified by e-mail when an error occurs after an update, you can xref:alerts-on-runtime-manager.adoc#create-an-alert[create an alert]. 

Because the alert is not tied to autoupdate failures, but any update (even self-triggered)

2024-02-01 21:05 UTC, luanamulesoft commented on cloudhub/modules/ROOT/pages/cloudhub-app-runtime-version-updates.adoc
> +To be notified by e-mail when an error occurs after an automated update, you can xref:alerts-on-runtime-manager.adoc#create-an-alert[create an alert].
Done!

2024-02-07 00:03 UTC, dmerlob approved these changes

2024-02-07 00:09 UTC, matbruc approved these changes
LGTM

2024-02-07 03:53 UTC, merged